### PR TITLE
feat: Logs Export API 

### PR DESCRIPTION
**Pull request by shivam-pareek**
**Title:** 
The endpoints of Logs Export API have been integrated in the Node SDK

**Related Issues:**
#135

### CODE REVIEW

**Comment by csgulati09** [comment]
Can you run the following commands and resolve if there is anything:

1. `npm run format:check`
2. `npm run format`
3. `npm run lint:check`
4. `npm run lint:fix`

**Comment by csgulati09** [comment]
We have a different structure in the API. 
Can we make another class, so that we can have `logs.exports` Since we might have other methods under logs in future

**Comment by shivam-pareek** [comment]
> Can you run the following commands and resolve if there is anything:
> 
> 1. `npm run format:check`
> 2. `npm run format`
> 3. `npm run lint:check`
> 4. `npm run lint:fix`

Ran and fixed!

**Comment by shivam-pareek** [comment]
> We have a different structure in the API. Can we make another class, so that we can have `logs.exports` Since we might have other methods under logs in future

Restructured accordingly.

**Review by csgulati09 — APPROVED** [review]

**Pull request merged**
